name: NequiCoiOS
options:
  bundleIdPrefix: com.wts.nequicooficial
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    TARGETED_DEVICE_FAMILY: 1
targets:
  NequiCoiOS:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.wts.nequicooficial.ios
      INFOPLIST_FILE: Sources/Info.plist
    dependencies:
      - framework: Frameworks/shared.xcframework
        embed: true
        codeSign: true
    scheme:
      testTargets: []

